spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.90.210:3306/tangyb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: tangyibo
    password: tangyibo
      
extract:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.90.119:3306/whistle?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: tangyibo
    password: tangyibo
  prefix: local_src_
  schema: 
      whistle:
        - ofuser_data
        - organization_data 
    